dysnix/nifi-registry/Chart.yaml
dysnix/nifi-registry/values.yaml

Raised NiFi version to 0.8.0. 
Signed-off-by: Rogier Dikkes <1867776+a-nldisr@users.noreply.github.com>

Raised NiFi version to 0.8.0

---

.gitignore
dysnix/app/Chart.lock
dysnix/app/Chart.yaml
dysnix/app/ci/ports-values.yaml
dysnix/app/templates/_helpers.tpl
dysnix/app/templates/_ingress.tpl
dysnix/app/templates/ingress.yaml
dysnix/app/templates/service.yaml

[dysnix/app] Update app chart

---

dysnix/geth/Chart.yaml
dysnix/geth/templates/_helpers.tpl
dysnix/geth/templates/statefulset.yaml
dysnix/geth/values.yaml

[geth] improve args passing, version bump

---

dysnix/geth/Chart.yaml
dysnix/geth/templates/_helpers.tpl

[geth] fix ws.* options

---

dysnix/nifi-registry/Chart.yaml
dysnix/nifi-registry/templates/statefulset.yaml
dysnix/nifi-registry/templates/tests/test-connection.yaml
dysnix/nifi-registry/values.yaml

Merged the changes from the two other pull requests on the issue, as they have gone stale.

[nifi-registry] Allow customization of images and tags.

---

dysnix/geth/Chart.yaml
dysnix/geth/templates/statefulset.yaml
dysnix/geth/values.yaml

geth version bump

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_nginx.txt

Add CORS headers to bsc nginx container

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_nginx.txt

[bsc] update nginx log format, add HSTS

---

dysnix/proxysql/Chart.yaml
dysnix/proxysql/templates/daemonset.yaml
dysnix/proxysql/templates/jobs.yaml
dysnix/proxysql/templates/statefullset.yaml
dysnix/proxysql/values.yaml

Use default values, when specialized value not set.

Add specific annotations and affinities for each k8s resource.

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

SSIA
It may help to pass CI too

[bsc] disable nodekey update by default

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_nginx.txt

[BSC] add nginx GET cache header 

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_nginx.txt

[bsc] add nginx cors cache post

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_nginx.txt

[bsc]fix nginx upstream

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configmap.yaml
dysnix/bsc/templates/configs/_env.txt
dysnix/bsc/templates/statefulset.yaml

We need to adjust timestamp variable in runtime w/o recreating pods

[bsc]Update health checks

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_env.txt
dysnix/bsc/values.yaml

[bsc]add helm values to configure health check variables

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_config.txt
dysnix/bsc/templates/statefulset.yaml

[bsc]enable diffsync

---

.github/workflows/lint-test.yaml
dysnix/app/Chart.yaml
dysnix/app/templates/deployment.yaml
dysnix/app/values.yaml
githooks/functions/libhelmlint.sh
githooks/functions/libkubeval.sh

[app] add serviceAccountName to deployment

---

dysnix/nifi-registry/Chart.yaml
dysnix/nifi-registry/values.yaml

Turn off postgres by default so that lint-test will succeed.

Turn off postgres by default

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

We need additional label to distinguish roles between releases. I don't wanna use chart name for this.

[bsc] add role label

---

dysnix/proxysql/Chart.yaml
dysnix/proxysql/templates/daemonset.yaml
dysnix/proxysql/templates/deployment.yaml
dysnix/proxysql/templates/statefullset.yaml
dysnix/proxysql/values.yaml

It may be usefull to access the proxysql admin interface locally to debug issues

Enable debugging container along the proxysql instance 

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_rsyncd.txt
dysnix/bsc/templates/scripts/_init_from_rsync.tpl
dysnix/bsc/templates/statefulset.yaml

* fix rsyncd config
* add readonly to rsyncd volume
* add one more rsync into initFromRsync

[bsc] fix rsyncd

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configmap.yaml
dysnix/bsc/templates/configs/_env.txt
dysnix/bsc/templates/scripts/_init_from_rsync.tpl
dysnix/bsc/templates/statefulset.yaml

* allow rsync to fail inside init-from-rsync
* adjust env and health checks as it should be

[bsc] fix init-from-rsync

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configmap.yaml
dysnix/bsc/templates/configs/_env.txt
dysnix/bsc/templates/configs/_probe-env.txt
dysnix/bsc/templates/statefulset.yaml

[bsc] fix health checks

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_init_from_rsync.tpl

* add more rsync tries to catch up

[bsc] improve init from rsync

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_init_from_rsync.tpl

[bsc] fix rsync init

---

dysnix/base/Chart.yaml
dysnix/base/examples/additional-env.yaml
dysnix/base/templates/lib/_containers.tpl
dysnix/base/templates/lib/_tpl.tpl

[base] improve additional env rendering

---

.github/ct.yaml
dysnix/eth-cache-proxy/Chart.yaml
dysnix/eth-cache-proxy/ci/probes-values.yaml
dysnix/eth-cache-proxy/templates/base-all.yaml
dysnix/eth-cache-proxy/templates/hpa.yaml
dysnix/eth-cache-proxy/templates/servicemonitor.yaml
dysnix/eth-cache-proxy/values.yaml

[eth-cache-proxy] initial 

---

dysnix/eth-cache-proxy/Chart.yaml
dysnix/eth-cache-proxy/templates/servicemonitor.yaml
dysnix/eth-cache-proxy/values.yaml

[eth-cache-proxy] enable monitoring

---

dysnix/eth-cache-proxy/Chart.yaml
dysnix/eth-cache-proxy/templates/servicemonitor.yaml
dysnix/eth-cache-proxy/values.yaml

* fix namespace
* disable monitoring by default

[eth-cache-proxy] fix service monitor

---

.github/ct.yaml
dysnix/ai-scale-doer/Chart.yaml
dysnix/ai-scale-doer/ci/probes-values.yaml
dysnix/ai-scale-doer/crds/ai-pod-autoscaler.yaml
dysnix/ai-scale-doer/default-configs.yml
dysnix/ai-scale-doer/templates/_default-configs.tpl
dysnix/ai-scale-doer/templates/_helpers.tpl
dysnix/ai-scale-doer/templates/base-all.yaml
dysnix/ai-scale-doer/templates/crs.yaml
dysnix/ai-scale-doer/templates/hpa.yaml
dysnix/ai-scale-doer/templates/rbac.yaml
dysnix/ai-scale-doer/templates/servicemonitor.yaml
dysnix/ai-scale-doer/templates/webhooks.yaml
dysnix/ai-scale-doer/values.yaml

add helm chart for deploy doer kubernetes operator service

ai-scale-doer chart

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_init_from_snaphot.tpl

[bsc] add zstd-compressed snapshot support

---

dysnix/base/Chart.yaml
dysnix/base/examples/additional-env.yaml
dysnix/base/templates/_configmap.tpl
dysnix/base/templates/_ingress.tpl
dysnix/base/templates/_secret.tpl
dysnix/base/templates/_service-account.tpl
dysnix/base/templates/_service.tpl
dysnix/base/templates/lib/_containers.tpl
dysnix/base/templates/lib/_tpl.tpl

[base] improve rendering with base.tpl.render

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/ilb.yaml
dysnix/bsc/templates/lb-p2p-discovery.yaml
dysnix/bsc/templates/lb-p2p.yaml
dysnix/bsc/templates/lb.yaml
dysnix/bsc/templates/scripts/_init_from_snaphot.tpl
dysnix/bsc/templates/service.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

* fix zstd support, switch to another init image
* add a label to manually remove nodes out of service

[bsc] add manual label

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml

[bsc] remove unused labels from sts selector

---

dysnix/base/Chart.yaml
dysnix/base/templates/_pod.tpl

[base] improve pod rendering

---

dysnix/base/Chart.yaml
dysnix/base/templates/_configmap.tpl
dysnix/base/templates/_ingress.tpl
dysnix/base/templates/_validate.tpl
dysnix/base/templates/lib/_ports.tpl

[base] improve ingress validation and configmap immutable field fix

---

dysnix/base/Chart.yaml
dysnix/base/examples/ingress.yaml
dysnix/base/templates/_ingress.tpl
dysnix/base/templates/_validate.tpl

[base] ingress cleanup and fixes

---

dysnix/base/Chart.yaml
dysnix/base/README.md
dysnix/base/templates/_ingress.tpl
dysnix/base/values.yaml

[base] add ingress.extraTlsHosts

---

dysnix/nifi-registry/templates/statefulset.yaml

Fixed the double command key in the statefulset.yaml file.

---

dysnix/base/Chart.yaml
dysnix/base/templates/_configmap.tpl
dysnix/base/templates/lib/_containers.tpl

[base] minor configmap and container render fixes

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

[bsc] make hostPort optional

---

dysnix/base/Chart.yaml
dysnix/base/templates/_ingress.tpl

[base] base fix ingress default path

---

dysnix/base/Chart.yaml
dysnix/base/examples/additional-env.yaml
dysnix/base/examples/multi-container.yaml
dysnix/base/templates/_pod.tpl
dysnix/base/templates/lib/_containers.tpl
dysnix/base/templates/lib/_tpl.tpl

[base] fix base.tpl.flatrender

---

dysnix/base/Chart.yaml
dysnix/base/templates/_configmap.tpl
dysnix/base/templates/_deployment.tpl
dysnix/base/templates/_ingress.tpl
dysnix/base/templates/_pod.tpl
dysnix/base/templates/_pvc.tpl
dysnix/base/templates/_secret.tpl
dysnix/base/templates/_service-account.tpl
dysnix/base/templates/_service.tpl
dysnix/base/templates/lib/_containers.tpl
dysnix/base/templates/lib/_tpl.tpl

[base] make base flatrender explicit

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

[bsc] fix long pod terminate, enable startup probe by default

---

dysnix/base/Chart.yaml
dysnix/base/templates/_component.tpl
dysnix/base/templates/_hpa.tpl
dysnix/base/templates/_validate.tpl
dysnix/base/values.yaml

[base] add HPA support

---

dysnix/base/Chart.yaml
dysnix/base/examples/multi-container.yaml
dysnix/base/templates/_component.tpl
dysnix/base/templates/_hpa.tpl
dysnix/base/values.yaml

[base] fix HPA

---

dysnix/base/Chart.yaml
dysnix/base/README.md
dysnix/base/templates/_pvc.tpl
dysnix/base/templates/lib/_volumes.tpl
dysnix/base/values.yaml

[base] add ephemeral emptyDir volume to persistence

---

dysnix/base/Chart.yaml
dysnix/base/templates/_pvc.tpl

[base] disable pvc for ephemeral persistence

---

dysnix/gcp-local-ssd-raid/Chart.yaml
dysnix/gcp-local-ssd-raid/templates/daemonset.yaml
dysnix/gcp-local-ssd-raid/values.yaml

[gcp-local-ssd-raid] add mkfs options

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/cronjob.yaml
dysnix/bsc/templates/scripts/_gcs_cleanup.tpl
dysnix/bsc/values.yaml

* add logging to gcs cleanup 
* remove credentials from stdout
* fix cronjob security context

[bsc] various fixes

---

.github/workflows/lint-test.yaml
dysnix/app/Chart.lock
dysnix/app/Chart.yaml
dysnix/app/templates/ingress.yaml
dysnix/base/Chart.yaml
dysnix/base/templates/_ingress.tpl

add ingressClassName support into app and base

---

dysnix/gcp-local-ssd-raid/Chart.yaml
dysnix/gcp-local-ssd-raid/templates/daemonset.yaml
dysnix/gcp-local-ssd-raid/values.yaml

[gcp-local-ssd-raid] add mnt dir override

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

[bsc] add hostPath support

---

dysnix/base/Chart.yaml
dysnix/rpcfast-gateway/Chart.yaml
dysnix/rpcfast-gateway/values.yaml

[rpcfast-gateway] add default ingress parameters

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configmap.yaml
dysnix/bsc/templates/cronjob-rbac.yaml
dysnix/bsc/templates/cronjob.yaml
dysnix/bsc/templates/scripts/_check_node_readiness.tpl
dysnix/bsc/templates/scripts/_prune.tpl
dysnix/bsc/templates/scripts/_rotate.tpl
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

* add rotation cronjob
* add readiness RPC endpoint variable
* add pipecommit, bump versions

[bsc] add rotation

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

[bsc] add persistdiff

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/configs/_nginx.txt
dysnix/bsc/values.yaml

[bsc] add CORS configuration variable 

---

dysnix/raw/Chart.yaml
dysnix/raw/README.md
dysnix/raw/templates/_helpers.tpl
dysnix/raw/templates/resources.yaml
dysnix/raw/values.yaml

add raw chart

---

dysnix/base/Chart.yaml
dysnix/base/README.md
dysnix/base/templates/_deployment.tpl
dysnix/base/templates/lib/_labels.tpl
dysnix/base/values.yaml

[base] make matchLabels configurable

---

dysnix/base/Chart.yaml
dysnix/base/templates/_service.tpl
dysnix/base/templates/lib/_ports.tpl

[base] use tpl for container and service ports

---

dysnix/base/Chart.yaml
dysnix/base/templates/_service.tpl
dysnix/base/templates/lib/_ports.tpl

[base] improve port and targetPort configuration

---

dysnix/allure-ee/Chart.yaml
dysnix/allure-ee/README.md
dysnix/allure-ee/requirements.lock
dysnix/allure-ee/requirements.yaml
dysnix/allure-ee/templates/_helpers.tpl
dysnix/allure-ee/templates/gateway-dep.yaml
dysnix/allure-ee/templates/gateway-svc.yaml
dysnix/allure-ee/templates/ingress.yaml
dysnix/allure-ee/templates/report-dep.yaml
dysnix/allure-ee/templates/report-pvc.yaml
dysnix/allure-ee/templates/report-svc.yaml
dysnix/allure-ee/templates/role.yaml
dysnix/allure-ee/templates/rolebinding.yaml
dysnix/allure-ee/templates/secret.yaml
dysnix/allure-ee/templates/serviceaccount.yaml
dysnix/allure-ee/templates/uaa-dep.yaml
dysnix/allure-ee/templates/uaa-svc.yaml
dysnix/allure-ee/values-custom.yaml
dysnix/allure-ee/values.yaml

add allure chart

---

dysnix/geth/Chart.yaml
dysnix/geth/templates/_helpers.tpl
dysnix/geth/values.yaml

[geth] add goerli

---

dysnix/nifi-registry/Chart.yaml

To release the nifi-registry ingress template changes I made [here](https://github.com/dysnix/charts/pull/205), I'm upping the chart version to trigger a release

Upping Chart.yaml version to release nifi registry chart

---

dysnix/app/Chart.yaml
dysnix/app/templates/configmaps.yaml
dysnix/app/templates/deployment.yaml
dysnix/app/templates/pvc.yaml
dysnix/app/templates/secrets.yaml
dysnix/app/templates/serviceaccount.yaml

[app] expand common labels and annotations to most resourses

---

dysnix/nifi-registry/Chart.yaml
dysnix/nifi-registry/tests/02-nifi-version-control.js

@daniel-yavorovich Thank you for merging #204 -- it looks like some bit rot caused a test to fail, so here's a quick fix.

[registry] fix test saving flow version

---

dysnix/geth/Chart.yaml
dysnix/geth/templates/_helpers.tpl
dysnix/geth/templates/secret.yaml
dysnix/geth/templates/statefulset.yaml
dysnix/geth/templates/svc.yaml
dysnix/geth/values.yaml

[geth] add authrpc support

---

dysnix/app/Chart.yaml
dysnix/app/templates/deployment.yaml
dysnix/app/values.yaml

[app] add basic extra containers to support sidecars

---

dysnix/app/Chart.yaml
dysnix/bsc/Chart.yaml
dysnix/geth/Chart.yaml
dysnix/nifi-registry/Chart.yaml
dysnix/pritunl/Chart.yaml
dysnix/proxysql/Chart.yaml

version bumps

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/lb-p2p-discovery.yaml
dysnix/bsc/templates/lb-p2p.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

* allow diffsync to be configurable, add tries-verify-mode
* allow p2p LB to work with not-ready pod

[bsc] minor updates

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

* Add resources to all containers

[bsc] add resources

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_sync_to_gcs.tpl
dysnix/bsc/values.yaml

* fix default resources
* improve sync-to-gcs upload error handling
* skip sync-to-gcs if recent init

[bsc] resources fixes, sync-to-gcs improvements

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/cronjob.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

* update api versions for cronjob
* replace external metrics image
* adjust sts to match a new image

[bsc] Replace external metrics

---

dysnix/proxysql/Chart.yaml
dysnix/proxysql/files/proxysql_cluster_healthcheck.sh
dysnix/proxysql/files/wait_queries_to_finish.sh
dysnix/proxysql/templates/configmap-healthcheck.yaml
dysnix/proxysql/templates/configmap-scripts.yaml
dysnix/proxysql/templates/daemonset.yaml
dysnix/proxysql/templates/deployment.yaml
dysnix/proxysql/templates/statefullset.yaml

Add script to wait for running proxy queries to finish because proxysql daemon does not wait for them to return before stopping the daemon.

[ProxySQL] Add preStop hook to wait for running proxy queries to finish

---

dysnix/app/Chart.yaml
dysnix/app/templates/deployment.yaml
dysnix/app/values.yaml

[app] add automountServiceAccountToken to pod spec

---

dysnix/app/Chart.yaml
dysnix/app/templates/_resources.tpl
dysnix/app/templates/hpa.yaml
dysnix/app/values.yaml

[app] add hpa support

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/ilb.yaml
dysnix/bsc/templates/lb-p2p-discovery.yaml
dysnix/bsc/templates/lb-p2p.yaml
dysnix/bsc/templates/lb.yaml
dysnix/bsc/values.yaml

[bsc] add LB annotations

---

dysnix/app/Chart.yaml
dysnix/app/templates/deployment.yaml
dysnix/app/values.yaml

[app] add minReadySeconds

---

dysnix/local-path-provisioner/Chart.yaml
dysnix/local-path-provisioner/README.md
dysnix/local-path-provisioner/templates/configmap.yaml
dysnix/local-path-provisioner/templates/deployment.yaml
dysnix/local-path-provisioner/templates/registry-secret.yaml
dysnix/local-path-provisioner/templates/serviceaccount.yaml
dysnix/local-path-provisioner/templates/storageclass.yaml
dysnix/local-path-provisioner/values.yaml

Bump local-path-provisioner from upstream

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_init_from_gcs.tpl
dysnix/bsc/templates/scripts/_sync_to_gcs.tpl
dysnix/bsc/values.yaml

* fix exclude bug
* update s5cmd version
* add upload stats

[bsc] update s5cmd version

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/pdb.yaml
dysnix/bsc/values.yaml

[bsc] add pdb support

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/pdb.yaml
dysnix/bsc/values.yaml

* fix default values
* add mutually exclusive logic
* add unhealthyPodEvictionPolicy

[bsc] fix PDB

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/pdb.yaml

[bsc] fix PDB zero values handling

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

[bsc] add topologySpreadConstraints

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_prune.tpl
dysnix/bsc/templates/scripts/_prune_block.tpl

[bsc] fix cache value

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/statefulset.yaml
dysnix/bsc/values.yaml

SSIA, [CloneSet lifecycle](https://openkruise.io/docs/user-manuals/cloneset#lifecycle-hook)
Nice features may be used for connection draining, f.e: 
```yaml
lifecycle:
preDelete:
markPodNotReady: true
```

[bsc] add CloneSet lifecycle support

---

dysnix/bsc/Chart.yaml
dysnix/bsc/templates/scripts/_prune_block.tpl

[bsc] fix prune-block for PBSS

---

dysnix/gcp-local-ssd-raid/Chart.yaml
dysnix/gcp-local-ssd-raid/templates/daemonset.yaml
dysnix/gcp-local-ssd-raid/values.yaml

[gcp-local-ssd-raid] add updateStrategy

---

dysnix/pritunl/Chart.yaml
dysnix/pritunl/templates/ingress.yaml
dysnix/pritunl/values.yaml

Not a big deal to set it after deploy, but I'm struggling a little bit because of this

Add Ingress className to pritunl helm chart

---

dysnix/gcp-local-nvme-raid/Chart.yaml
dysnix/gcp-local-nvme-raid/templates/daemonset.yaml
dysnix/gcp-local-nvme-raid/values.yaml

[gcp-local-nvme-raid] add raidOpts

---

dysnix/app/Chart.yaml
dysnix/app/templates/_containers.tpl

Update `merge` function to `mustMergeOverwrite`
because `merge` isn't working correctly.
`must` used to throw an error if merge couldn't be done.
https://github.com/helm/helm/issues/5238

[app] Fix merge function
