dysnix/nifi-registry/Chart.yaml, dysnix/nifi-registry/templates/statefulset.yaml, dysnix/nifi-registry/values.yaml
This will allow to pass additional environment variables to the initcontainers. In our case we use it to set the `GIT_SSH_COMMAND` environment variable in the `git-clone` initcontainer.
=> add extraenvs option for initcontainers

dysnix/proxysql/Chart.yaml, dysnix/proxysql/templates/service.yaml
Removing topologyKeys from the service.yaml template as it was deprecated from Kubernetes v1.21 and bumped the chart version.
=> Remove topology keys

dysnix/nifi-registry/Chart.yaml, dysnix/nifi-registry/templates/statefulset.yaml, dysnix/nifi-registry/values.yaml
If /home/nifi/.ssh is not writable, JGit can't create a known_hosts.lock file and throws an exception.  This makes it impossible for NiFi Registry to check in a commit to a Git repository via SSH, and leaves NiFi in a state where there is no checked-in revision of a process group.
Also, extraEnvs was broken because indent was being used instead of nindent.
Finally, the values.yaml comments show creating an SSH private key named identity, but the chart actually expects the private key to be named id_rsa.
=> NiFi Registry JGit SSH client fails if /home/nifi/.ssh is not writable

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/_helpers.tpl, dysnix/bsc/templates/configmap.yaml, dysnix/bsc/templates/configs/_config.txt, dysnix/bsc/templates/configs/_nginx.txt, dysnix/bsc/templates/scripts/_generate_node_config.tpl, dysnix/bsc/templates/scripts/_get_nodekey_ip.tpl, dysnix/bsc/templates/scripts/_init_from_snaphot.tpl, dysnix/bsc/templates/serviceaccount.yaml, dysnix/bsc/templates/statefulset.yaml, dysnix/bsc/values.yaml
* add [CloneSet](https://openkruise.io/docs/user-manuals/cloneset) support to handle custom scale-up/scale-down
* add nodekey pick-up script based on pod's IP address, no other options with CloneSet
* allow trusted nodes list download from GCS to handle long lists, no other options with CloneSet
* minor BSC node config changes to simple file concatenation
* add nginx backend override variable
* add service account and use it in controller
* add mbuffer to the pipeline with zstd-compressed archive to speedup things
=> [bsc] add CloneSet support, various fixes and improvements

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/alerts.yaml, dysnix/bsc/templates/backendconfig.yaml, dysnix/bsc/templates/configmap.yaml, dysnix/bsc/templates/cronjob-rbac.yaml, dysnix/bsc/templates/cronjob.yaml, dysnix/bsc/templates/hpa.yaml, dysnix/bsc/templates/ilb.yaml, dysnix/bsc/templates/ingress.yaml, dysnix/bsc/templates/lb-p2p-discovery.yaml, dysnix/bsc/templates/lb-p2p.yaml, dysnix/bsc/templates/lb.yaml, dysnix/bsc/templates/mci.yaml, dysnix/bsc/templates/mcs.yaml, dysnix/bsc/templates/scripts/_cron.tpl, dysnix/bsc/templates/scripts/_gcs_cleanup.tpl, dysnix/bsc/templates/scripts/_init_from_gcs.tpl, dysnix/bsc/templates/scripts/_init_from_rsync.tpl, dysnix/bsc/templates/scripts/_init_from_snaphot.tpl, dysnix/bsc/templates/scripts/_prune.tpl, dysnix/bsc/templates/scripts/_sync_to_gcs.tpl, dysnix/bsc/templates/secret.yaml, dysnix/bsc/templates/service.yaml, dysnix/bsc/templates/serviceaccount.yaml, dysnix/bsc/templates/servicemonitor.yaml, dysnix/bsc/templates/statefulset.yaml, dysnix/bsc/values.yaml
* add init `init-from-gcs` using [s5cmd](https://github.com/peak/s5cmd)
* add init `sync-to-gcs` using s5cmd
* add sidecar `gcs-cleanup` to remove unneded files in the cloud after `sync-to-gcs`
* add init `prune` to perform [node pruning](https://docs.binance.org/smart-chain/developer/fullnode.html#storage)
* add cronjobs to trigger `sync-to-gcs` and `prune`
* add/fix labels
* various small fixes
* no breaking changes, bump minor version due to a lot of changes only
=> [bsc] GCS init/sync, prune, various improvements

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/_helpers.tpl, dysnix/bsc/templates/configmap.yaml, dysnix/bsc/templates/configs/_nginx.txt, dysnix/bsc/templates/force-scale-helper.yaml, dysnix/bsc/templates/force-scale-trigger.yaml, dysnix/bsc/templates/scripts/_controller_hook.tpl, dysnix/bsc/templates/scripts/_init_from_gcs.tpl, dysnix/bsc/templates/scripts/_update_pod_deletion_cost.tpl, dysnix/bsc/templates/serviceaccount.yaml, dysnix/bsc/templates/statefulset.yaml, dysnix/bsc/values.yaml
* enable nginx reply compression by default
* add update-pod-deletion-cost sidecar to use it with controlled scale down
* add one more controller (scale-trigger) to work-around local SSD PV [autoscaler issue](https://github.com/kubernetes/autoscaler/issues/2145). Another possible way is to switch from PV & PVC to hostPath volumes
* add scale-helper to propagate scaling from main controller to scale-trigger 
* various small fixes
=> [bsc] scaling improvements

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/scripts/_init_from_gcs.tpl, dysnix/bsc/values.yaml
We cannot stabilize init-from-gsc for now, thus we enforce full cleanup by default in case of source timestamp changes
=> [bsc] enable forced cleanup with init-from-gcs by default

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/cronjob.yaml, dysnix/bsc/templates/statefulset.yaml
Related to [this helm bug](https://github.com/helm/helm/issues/7090). We may use negative replicaCount to keep existing replicas during helm upgrade
=> [bsc] add support of controller scaling

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/configmap.yaml, dysnix/bsc/templates/scripts/_prune_block.tpl, dysnix/bsc/templates/statefulset.yaml, dysnix/bsc/values.yaml
[prune-block](https://github.com/bnb-chain/bsc/pull/543) allows to save space if you don't need historical data. May be useful with bootnodes w/o RPC.
=> [bsc] add prune-block init

dysnix/nifi-registry/Chart.yaml, dysnix/nifi-registry/templates/statefulset.yaml, dysnix/nifi-registry/values.yaml
This PR adds the ability to configure NiFi Registry's bundle provider per the following sources:
- https://github.com/apache/nifi/blob/main/nifi-registry/nifi-registry-core/nifi-registry-docker/dockerhub/sh/update_bundle_provider.sh
- https://nifi.apache.org/docs/nifi-registry-docs/html/administration-guide.html#bundle-persistence-providers
=> [nifi-registry] added bundle provider configuration

dysnix/nifi-registry/templates/ingress.yaml
I'm trying to deploy nifi-registry on k8s `v1.24.2` but the ingress templates do not currently support `networking.k8s.io/v1`
I've added this functionality, basing it on the existing template in `charts/dysnix/dshackle/templates/ingress.yaml`
=> Upgrading nifi-registry ingress to support k8s >=1.19

.github/workflows/nifi-registry-tests.yaml, dysnix/nifi-registry/Chart.yaml, dysnix/nifi-registry/tests/02-nifi-values.yaml, dysnix/nifi-registry/tests/02-registry-values.yaml
Hi @dennybaa it's unfortunate that the NiFi Registry end-to-end test cost you time when it broke as you were merging https://github.com/dysnix/charts/pull/201 .  The reason the test broke was because the NiFi Helm chart referenced a version of the Zookeeper Helm chart that no longer existed (see https://github.com/cetic/helm-nifi/issues/256).  I fixed that with an update to https://github.com/cetic/helm-nifi/pull/218 and this PR references the new tip of that branch.
However, having this end-to-end test has already saved us all time.  For example, the commit https://github.com/dysnix/charts/commit/500536e89b98e422c2255fb465a53cb506be391e was in https://github.com/dysnix/charts/pull/201 because the test failed (see https://github.com/michael81877/dysnix-charts/runs/6572915433?check_suite_fo …
=> [nifi-registry] bump NiFi zookeeper chart version

dysnix/proxysql/Chart.yaml, dysnix/proxysql/files/proxysql_cluster_healthcheck.sh, dysnix/proxysql/templates/configmap-healthcheck.yaml, dysnix/proxysql/templates/configmap.yaml, dysnix/proxysql/templates/daemonset.yaml, dysnix/proxysql/templates/deployment.yaml, dysnix/proxysql/templates/secret-healthcheck.yaml, dysnix/proxysql/templates/statefullset.yaml, dysnix/proxysql/values.yaml
And if selected, restart the proxysql daemon container.
This healthchecks are useful in a proxysql-cluster environment to avoid syncing issues, when the cluster config differs after a long time.
=> [ProxySQL] Add healthchek sidecar for cluster checks

dysnix/nifi-registry/templates/statefulset.yaml, dysnix/nifi-registry/values.yaml
Between nifi-registry v0.8.0 and v1.19.1 this statement was added in `/opt/nifi-registry/scripts/update_flow_provider.sh`:
```
if [ ! -z "$NIFI_REGISTRY_GIT_REPO" ]; then
add_property "Remote Clone Repository" "${NIFI_REGISTRY_GIT_REPO:-}"
fi
```
This commit adds that statement so the `git clone` will work with v0.8.0.
It should be noted that `git clone` does not [currently work with ssh authentication](https://issues.apache.org/jira/browse/NIFI-8867).
I also added the option to use a k8s secret for the git password.
=> fix: nifi-registry git clone in v0.8.0

dysnix/raw/Chart.yaml, dysnix/raw/templates/resources.yaml
We're having errors while running `helm lint`:
```
[ERROR] templates/resources.yaml: unable to parse YAML: invalid Yaml document separator:
```
This PR adds missing whitespace after yaml separator when creating multiple resources.
=> [raw] fix missing whitespace after yaml separator

dysnix/app/Chart.yaml, dysnix/app/README.md, dysnix/app/templates/_resources.tpl, dysnix/app/templates/pdb.yaml, dysnix/app/templates/rbac.yaml, dysnix/app/templates/secrets.yaml, dysnix/app/templates/service.yaml, dysnix/app/values.yaml
* add PDB, some handling of empty and 0 values
* add Role & RoleBinding
* add extra selectors for service to allow to match extra labels compared to controller's matchLabels. It's useful to manipulate by these extra labels to include/exclude pods into service without bothering controller's logic
* style
* add `stringData` work-around in `Secret`, see [this helm/k8s issue](https://github.com/helm/helm/issues/10010#issuecomment-1671013348)
=> [app] add pdb and rbac, various

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/configs/_config.txt, dysnix/bsc/templates/statefulset.yaml, dysnix/bsc/values.yaml
This PR will remove deprecated `--pipecommit` and `--diffsync` while also introducing some extra arguments:
- `--cache.preimages` is now configurable
- `--txlookuplimit` is now configurable for BSC 1.2.x and older versions, set to `null` to be omitted
- `--history.transactions` is now available for BSC >=1.3.x, replacing `--txlookuplimit` argument, by default disabled
- `--pruneancient` is now available
=> [bsc] improve CLI args

dysnix/nifi-registry/Chart.yaml, dysnix/nifi-registry/templates/statefulset.yaml
This bugfix is completely analogous to the pull request https://github.com/cetic/helm-nifi/pull/314.
This pull request allows apache/nifi-registry versions >=0.19.0 to be released with this helm chart.
As described in issue https://github.com/cetic/helm-nifi/issues/313, this only required the keystore type to be explicitly set to JKS when calling keytool to be compatible with Java 11.
This change is backward compatible with Java 8.
=> [nifi-registry] Made compatible with apache/nifi >= 1.19.0

dysnix/proxysql/Chart.yaml, dysnix/proxysql/files/proxysql_cluster_healthcheck.sh, dysnix/proxysql/files/wait_queries_to_finish.sh, dysnix/proxysql/templates/_helpers.tpl, dysnix/proxysql/templates/configmap-healthcheck.yaml, dysnix/proxysql/templates/daemonset.yaml, dysnix/proxysql/templates/deployment.yaml, dysnix/proxysql/templates/jobs.yaml, dysnix/proxysql/templates/secret-healthcheck.yaml, dysnix/proxysql/templates/statefullset.yaml, dysnix/proxysql/values.yaml
*  Improve and clean up health check scripts
* Add startup, readiness and liveness probes to work accordingly to k8s docs
* Remove not needed healthcheck container (the proxysql docker image has now the necessary mysql/mariadb clients for the checks)
* Rework init job
=> [ProxySQL] lifecycle improvements

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/scripts/_init_from_gcs.tpl, dysnix/bsc/values.yaml
* fail init-from-gcs when no ojects copied from cloud storage
* bump versions
=> [bsc] minor fix init-from-gcs

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/scripts/_check_node_readiness.tpl, dysnix/bsc/templates/scripts/_sync_to_gcs.tpl, dysnix/bsc/templates/statefulset.yaml, dysnix/bsc/values.yaml
* revert ancient upload with pruneancient, as ancient dir is not empty and holds some data
* add liveness probe to metric
* bump versions
=> [bsc] various minor fixes

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/scripts/_init_from_gcs.tpl, dysnix/bsc/values.yaml
We may speed things up using more workers for s5cmd to copy chain state alone
=> [bsc] speedup init-from-gcs when a source snapshot is pruned

dysnix/bsc/Chart.yaml, dysnix/bsc/templates/scripts/_init_from_gcs.tpl, dysnix/bsc/values.yaml
Fixes an issue introduced by #309
=> [bsc] fix init-from-gcs with pruneancient

dysnix/gcp-local-ssd-raid/Chart.yaml, dysnix/gcp-local-ssd-raid/templates/daemonset.yaml
When `STARTUP_SCRIPT` has successfully finished for the first time, it will crash with an error on all subsequent pod restarts.
This PR is attempt to fix this behavior.
* fixing check when raid device is already present
* adding check when raid device is already mounted at `$mnt_dir`
=> [gcp-local-ssd-raid] fix init script crash on subsequent restarts
